fix(CI-CD): Adds check to fail at versioning task if version is not appropriately determined.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,7 @@ jobs:
     environment: production
     permissions:
       contents: read
+      id-token: write
     steps:
       - name: Checkout code.
         uses: actions/checkout@v4
@@ -25,7 +26,12 @@ jobs:
       - name: Determine next version.
         id: version
         run: |
-          echo "version=$(poetry run semantic-release version --print)" >> $GITHUB_OUTPUT
+          version=$(poetry run semantic-release version --print-tag)
+          if [ -z "$version" ]; then
+            echo "Failed to determine the version tag. Exiting with error."
+            exit 1
+          fi
+          echo "version=$version" >> $GITHUB_ENV
           echo "Building version: $version 🛠️."
 
   build-push:
